services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      VITE_STAGE: ${STAGE}
    networks: [shared_net]

networks:
  shared_net:
    external: true
